import { expect, test } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

// End-to-end proof (AC.4) that a saved-query localStorage string generated by
// the legacy sql.js build (commit c016616) restores correctly in the HEAD
// baked-data build via the #saved-queries-select dropdown restore path (which the
// URL-hash suite never exercises). The fixture is a v2 SavedQuery captured from
// the old dev server: 1 small / 3 medium / 2 large houses, 13 randomly-sampled
// pokemon, and ≥3 cart entries.

const fixturePath = join(
  dirname(fileURLToPath(import.meta.url)),
  'fixtures',
  'legacy-saved-query.json',
)
const fixture = JSON.parse(readFileSync(fixturePath, 'utf8')) as {
  sourceCommit: string
  capturedAt: string
  stored: string
  decoded: Array<{
    title: string
    timestamp: number
    version: number
    small: number
    medium: number
    large: number
    pokemon: string[]
    cart: Array<{ houseId: string; name: string }>
  }>
}

test.describe('Legacy saved-query loading (sql.js → baked-data)', () => {
  test('restores a legacy c016616 saved-query end-to-end in the HEAD build', async ({ page }) => {
    test.setTimeout(40_000)

    // Seed localStorage before the app mounts so loadSavedQueries() reads it.
    await page.addInitScript((stored) => {
      localStorage.setItem('pokehousing_saved_queries', stored)
    }, fixture.stored)
    await page.goto('/')

    // Dropdown populates with the fixture's title.
    const select = page.locator('#saved-queries-select')
    await expect(select).toBeVisible({ timeout: 30_000 })
    await expect(select).toContainText(fixture.decoded[0].title)

    // Select the entry to trigger the selectedTimestamp watch → restoreState.
    await select.selectOption(String(fixture.decoded[0].timestamp))

    // House counts restore (BFormSpinbutton renders its id on the inner output).
    await expect(page.locator('#house-small')).toHaveText('1', { timeout: 30_000 })
    await expect(page.locator('#house-medium')).toHaveText('3', { timeout: 30_000 })
    await expect(page.locator('#house-large')).toHaveText('2', { timeout: 30_000 })

    // All 13 sampled pokemon appear across the results section.
    const results = page.getByTestId('results')
    await expect(results).toBeVisible({ timeout: 30_000 })
    for (const name of fixture.decoded[0].pokemon) {
      await expect(results).toContainText(name, { timeout: 30_000 })
    }

    // No error or unhoused banner.
    await expect(page.getByTestId('error')).toHaveCount(0)
    await expect(page.getByTestId('unhoused')).toHaveCount(0)

    // The restoringQuery gate terminates: the catalog-loading spinner is gone.
    await expect(page.getByTestId('catalog-loading')).toHaveCount(0)

    // Cart restores: correct count and every expected item name present, scoped
    // to the cart-items panel (a bare `item-name` locator would also match the
    // unrelated `item-name` testid inside HouseRecord.vue's cart-coverage table).
    const cartItems = page.getByTestId('cart-item')
    await expect(cartItems).toHaveCount(fixture.decoded[0].cart.length, { timeout: 5000 })
    const expectedNames = new Set(fixture.decoded[0].cart.map((entry) => entry.name))
    for (const name of expectedNames) {
      await expect(page.getByTestId('cart-items')).toContainText(name, { timeout: 5000 })
    }
  })
})
