import { expect, test } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

// Existing suites model a returning visitor: seeding the tour's seen flag keeps
// the first-run guided tour from auto-starting (and blocking the page) mid-test.
// Only e2e/onboarding.spec.ts exercises the auto-start path.
test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('pokehousing_tour_seen', '1'))
})

// End-to-end proof (AC.3) that a URL hash generated by the legacy sql.js build
// (commit c016616) restores correctly in the HEAD baked-data build. The fixture
// is a v2 SharedState captured from the old dev server: 1 small / 3 medium /
// 2 large houses, 13 randomly-sampled pokemon, and ≥3 cart entries.

const fixturePath = join(dirname(fileURLToPath(import.meta.url)), 'fixtures', 'legacy-island.json')
const fixture = JSON.parse(readFileSync(fixturePath, 'utf8')) as {
  sourceCommit: string
  capturedAt: string
  hash: string
  decoded: {
    version: number
    small: number
    medium: number
    large: number
    pokemon: string[]
    cart: Array<{ houseId: string; name: string }>
  }
}

test.describe('Legacy hash loading (sql.js → baked-data)', () => {
  test('restores a legacy c016616 hash end-to-end in the HEAD build', async ({ page }) => {
    test.setTimeout(40_000)

    await page.goto(`/#${fixture.hash}`)

    // House counts restore (BFormSpinbutton renders its id on the inner output).
    await expect(page.locator('#house-small')).toHaveText('1', { timeout: 30_000 })
    await expect(page.locator('#house-medium')).toHaveText('3', { timeout: 30_000 })
    await expect(page.locator('#house-large')).toHaveText('2', { timeout: 30_000 })

    // All 13 sampled pokemon appear across the results section.
    const results = page.getByTestId('results')
    await expect(results).toBeVisible({ timeout: 30_000 })
    for (const name of fixture.decoded.pokemon) {
      await expect(results).toContainText(name, { timeout: 30_000 })
    }

    // No error or unhoused banner.
    await expect(page.getByTestId('error')).toHaveCount(0)
    await expect(page.getByTestId('unhoused')).toHaveCount(0)

    // Cart restores: correct count and every expected item name present.
    const cartItems = page.getByTestId('cart-item')
    await expect(cartItems).toHaveCount(fixture.decoded.cart.length, { timeout: 5000 })
    const expectedNames = new Set(fixture.decoded.cart.map((entry) => entry.name))
    for (const name of expectedNames) {
      await expect(page.getByTestId('cart-items')).toContainText(name, { timeout: 5000 })
    }
  })
})
